services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    env_file:
      - db/.env
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
  goserver:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    container_name: goserver
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
volumes:
  test_db_data: